object DigitForm: TDigitForm
  Left = 1065
  Top = 684
  AlphaBlend = True
  AlphaBlendValue = 225
  BorderStyle = bsNone
  Caption = 'DigitForm'
  ClientHeight = 432
  ClientWidth = 421
  Color = 10930928
  TransparentColor = True
  TransparentColorValue = 10930928
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'MS Sans Serif'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  Position = poMainFormCenter
  OnClose = FormClose
  OnCreate = FormCreate
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
  object cxButton1: TcxButton
    Left = 8
    Top = 335
    Width = 183
    Height = 90
    Caption = '0'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 0
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = ButtonClick
  end
  object cxButton2: TcxButton
    Left = 195
    Top = 335
    Width = 90
    Height = 90
    Caption = ','
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 1
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = cxButton2Click
  end
  object cxButton3: TcxButton
    Left = 8
    Top = 242
    Width = 90
    Height = 90
    Caption = '1'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 2
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = ButtonClick
  end
  object cxButton4: TcxButton
    Left = 101
    Top = 242
    Width = 90
    Height = 90
    Caption = '2'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 3
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = ButtonClick
  end
  object cxButton5: TcxButton
    Left = 195
    Top = 242
    Width = 90
    Height = 90
    Caption = '3'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 4
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = ButtonClick
  end
  object cxButton6: TcxButton
    Left = 8
    Top = 148
    Width = 90
    Height = 90
    Caption = '4'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 5
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = ButtonClick
  end
  object cxButton7: TcxButton
    Left = 101
    Top = 148
    Width = 90
    Height = 90
    Caption = '5'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 6
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = ButtonClick
  end
  object cxButton8: TcxButton
    Left = 195
    Top = 148
    Width = 90
    Height = 90
    Caption = '6'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 7
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = ButtonClick
  end
  object cxButton9: TcxButton
    Left = 8
    Top = 55
    Width = 90
    Height = 90
    Caption = '7'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 8
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = ButtonClick
  end
  object cxButton10: TcxButton
    Left = 101
    Top = 55
    Width = 90
    Height = 90
    Caption = '8'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 9
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = ButtonClick
  end
  object cxButton11: TcxButton
    Left = 195
    Top = 55
    Width = 90
    Height = 90
    Caption = '9'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 10
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = ButtonClick
  end
  object cxButton12: TcxButton
    Left = 289
    Top = 55
    Width = 118
    Height = 118
    Caption = 'Esc'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 11
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = cxButton12Click
  end
  object cxButton13: TcxButton
    Left = 289
    Top = 177
    Width = 118
    Height = 124
    Caption = '<-'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 12
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = cxButton13Click
  end
  object cxButton14: TcxButton
    Left = 290
    Top = 305
    Width = 118
    Height = 120
    Caption = 'Enter'
    LookAndFeel.NativeStyle = False
    SpeedButtonOptions.CanBeFocused = False
    SpeedButtonOptions.Flat = True
    TabOrder = 13
    Font.Charset = RUSSIAN_CHARSET
    Font.Color = clWindowText
    Font.Height = -35
    Font.Name = 'Tahoma'
    Font.Style = [fsBold]
    ParentFont = False
    OnClick = cxButton14Click
  end
  object Edit1: TEdit
    Left = 9
    Top = 7
    Width = 398
    Height = 45
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clDefault
    Font.Height = -35
    Font.Name = 'MS Sans Serif'
    Font.Style = []
    ParentFont = False
    PasswordChar = '*'
    TabOrder = 14
    OnKeyUp = Edit1KeyUp
  end
end
